-- PostgreSQL setup for cleaned CSV files generated by data_analysis.py
-- Run this file with psql (not pgAdmin query tool) because it uses \copy.

-- 1) Create database
DROP DATABASE IF EXISTS learndb;
CREATE DATABASE learndb;

\c learndb;

-- 2) Create dimension tables
CREATE TABLE customers (
    customerkey INT PRIMARY KEY,
    gender TEXT,
    name TEXT,
    city TEXT,
    state_code TEXT,
    state TEXT,
    zip_code TEXT,
    country TEXT,
    continent TEXT,
    birthday DATE,
    age INT,
    age_group TEXT
);

CREATE TABLE products (
    productkey INT PRIMARY KEY,
    product_name TEXT,
    brand TEXT,
    color TEXT,
    unit_cost_usd NUMERIC(12,2),
    unit_price_usd NUMERIC(12,2),
    subcategorykey INT,
    subcategory TEXT,
    categorykey INT,
    category TEXT
);

CREATE TABLE stores (
    storekey INT PRIMARY KEY,
    country TEXT,
    state TEXT,
    square_meters NUMERIC(10,2),
    open_date DATE
);

CREATE TABLE exchange_rates (
    date DATE,
    currency TEXT,
    exchange NUMERIC(14,6),
    PRIMARY KEY (date, currency)
);

-- 3) Create fact table (from Sales_Cleaned.csv)
CREATE TABLE sales (
    order_number INT,
    line_item INT,
    order_date DATE,
    delivery_date DATE,
    customerkey INT,
    storekey INT,
    productkey INT,
    quantity INT,
    currency_code TEXT,
    unit_cost_usd NUMERIC(12,2),
    unit_price_usd NUMERIC(12,2),
    revenue_usd NUMERIC(14,2),
    cost_usd NUMERIC(14,2),
    profit_usd NUMERIC(14,2),
    profit_margin NUMERIC(7,2),
    delivery_days NUMERIC(10,2),
    year INT,
    quarter INT,
    month INT,
    month_name TEXT,
    day_of_week TEXT,
    PRIMARY KEY (order_number, line_item),
    FOREIGN KEY (customerkey) REFERENCES customers(customerkey),
    FOREIGN KEY (storekey) REFERENCES stores(storekey),
    FOREIGN KEY (productkey) REFERENCES products(productkey)
);

-- 4) Import data from local CSV files (client-side paths)
\copy customers FROM 'D:/React/learndb/Customers_Cleaned.csv' CSV HEADER;
\copy products FROM 'D:/React/learndb/Products_Cleaned.csv' CSV HEADER;
\copy stores FROM 'D:/React/learndb/Stores_Cleaned.csv' CSV HEADER;
\copy exchange_rates FROM 'D:/React/learndb/Exchange_Rates_Cleaned.csv' CSV HEADER;
\copy sales FROM 'D:/React/learndb/Sales_Cleaned.csv' CSV HEADER;

-- 5) Performance indexes
CREATE INDEX idx_sales_order_date ON sales(order_date);
CREATE INDEX idx_sales_customer ON sales(customerkey);
CREATE INDEX idx_sales_product ON sales(productkey);
CREATE INDEX idx_sales_store ON sales(storekey);
CREATE INDEX idx_sales_currency_date ON sales(currency_code, order_date);

-- 6) Quick checks
SELECT 'customers' AS table_name, COUNT(*) AS rows FROM customers
UNION ALL
SELECT 'products', COUNT(*) FROM products
UNION ALL
SELECT 'stores', COUNT(*) FROM stores
UNION ALL
SELECT 'exchange_rates', COUNT(*) FROM exchange_rates
UNION ALL
SELECT 'sales', COUNT(*) FROM sales;

-- Example KPI
SELECT
    COUNT(DISTINCT order_number) AS total_orders,
    COUNT(DISTINCT customerkey) AS total_customers,
    ROUND(SUM(revenue_usd), 2) AS total_revenue_usd,
    ROUND(SUM(profit_usd), 2) AS total_profit_usd,
    ROUND((SUM(profit_usd) / NULLIF(SUM(revenue_usd), 0)) * 100, 2) AS margin_pct
FROM sales;
